-- News & Resources seed data for BetRollover
-- Run: docker compose exec -T postgres psql -U betrollover -d betrollover < database/seeds/news-resources-seed.sql
-- Or: psql -h localhost -p 5435 -U betrollover -d betrollover -f database/seeds/news-resources-seed.sql

-- =============================================================================
-- NEWS ARTICLES (Football news, transfers, rumours, gossip)
-- Uses actual dates when these events occurred (2023-2025)
-- =============================================================================
INSERT INTO news_articles (slug, title, excerpt, content, category, featured, meta_description, published_at) VALUES
-- News
('premier-league-title-race-heats-up', 'Premier League title race heats up as top four battle intensifies', 'The race for the Premier League crown is wide open with multiple clubs in contention as we approach the business end of the season.', 'The Premier League title race has taken another dramatic turn with key results over the weekend. Manchester City, Arsenal, Liverpool, and Chelsea remain in the hunt, with each side showing both strength and vulnerability. The upcoming fixtures will be crucial in determining who lifts the trophy in May. Key injuries and squad depth could prove decisive in the final stretch.', 'news', true, 'Latest Premier League title race analysis and standings', '2025-04-20 14:00:00'),
('africa-cup-of-nations-2025-preview', 'Africa Cup of Nations 2025: Full preview and predictions', 'The continent''s biggest football tournament returns with host nation Morocco ready to welcome Africa''s finest.', 'The Africa Cup of Nations 2025 promises to be a spectacular celebration of African football. Host nation Morocco will be looking to add a second AFCON title to their 1976 triumph. Defending champions Ivory Coast face a tough challenge, while Ghana, Nigeria, Senegal, and Egypt will all be among the favourites. The tournament format and venue details have been confirmed, with matches spread across several Moroccan cities.', 'news', true, 'AFCON 2025 preview, fixtures, and predictions', '2024-12-15 10:00:00'),
('champions-league-knockout-draw-reaction', 'Champions League knockout draw: Analysts react to last-16 pairings', 'The draw for the Champions League round of 16 has thrown up several mouth-watering ties.', 'European football''s elite now know their paths to the final. The draw produced several intriguing matchups, with traditional powerhouses set to clash in the round of 16. Spanish, English, German, and Italian clubs will battle for a place in the quarter-finals. The first legs are scheduled for February, with the return fixtures in March.', 'news', false, 'Champions League last-16 draw analysis', '2024-12-18 12:00:00'),
('ghana-premier-league-midseason-review', 'Ghana Premier League mid-season review: Surprises and standout performers', 'The Ghana Premier League reaches its halfway point with unexpected leaders and thrilling matches.', 'The domestic season in Ghana has provided plenty of drama. Traditional giants have been challenged by emerging clubs, and the race for continental qualification remains wide open. Key signings and managerial changes have shaped the campaign so far. We analyse the standout performers and predict how the second half might unfold.', 'news', false, 'Ghana Premier League mid-season analysis', '2025-01-10 16:00:00'),

-- Transfer Rumours
('mbappe-real-madrid-latest', 'Mbappé to Real Madrid: Latest reports suggest deal is imminent', 'Sources close to both clubs indicate that the French superstar could finally complete his long-awaited move to the Spanish capital.', 'Kylian Mbappé''s future has dominated headlines for months, and the latest reports suggest he could finally be on his way to Real Madrid. The French forward''s contract situation at Paris Saint-Germain has been the subject of intense speculation. If the move materialises, it would represent one of the biggest transfers in football history. Both clubs have remained tight-lipped, but insiders suggest an announcement could come soon.', 'transfer_rumour', true, 'Mbappé Real Madrid transfer latest news', '2024-05-15 09:00:00'),
('salah-saudi-arabia-january', 'Mohamed Salah Saudi Arabia move: January bid expected', 'Saudi Pro League clubs are reportedly preparing a fresh approach for the Liverpool star in the winter window.', 'Mohamed Salah has been a long-term target for Saudi Arabian clubs, and reports suggest a substantial bid could be tabled in the January transfer window. Liverpool have previously resisted approaches, but the financial power of the Saudi Pro League could test their resolve. The Egyptian''s contract situation and his importance to Liverpool make this one of the most watched sagas of the season.', 'transfer_rumour', false, 'Salah Saudi Arabia transfer rumours', '2025-01-25 11:00:00'),
('osimhen-chelsea-arsenal-race', 'Osimhen race heats up: Chelsea and Arsenal both keen on Napoli striker', 'The Nigerian striker is expected to leave Napoli next summer with multiple Premier League clubs interested.', 'Victor Osimhen''s future at Napoli has been the subject of intense speculation. Chelsea and Arsenal are both reportedly monitoring the situation closely, with the striker''s release clause making a summer move feasible. His goalscoring record in Serie A and the Champions League has made him one of Europe''s most sought-after forwards. A bidding war could develop when the transfer window opens.', 'transfer_rumour', false, 'Osimhen Chelsea Arsenal transfer news', '2025-05-20 14:00:00'),

-- Confirmed Transfers (actual dates when these moves happened)
('bellingham-real-madrid-complete', 'Jude Bellingham completes record move to Real Madrid', 'The England midfielder has signed a six-year deal with the Spanish giants in a deal worth over €100 million.', 'Real Madrid have officially announced the signing of Jude Bellingham from Borussia Dortmund. The 20-year-old England international has put pen to paper on a six-year contract. The transfer fee is believed to be in excess of €100 million, making him one of the most expensive British players in history. Bellingham will wear the number 5 shirt and is expected to be a key part of Madrid''s midfield for years to come.', 'confirmed_transfer', true, 'Jude Bellingham Real Madrid transfer confirmed', '2023-06-14 12:00:00'),
('rice-arsenal-official', 'Declan Rice joins Arsenal in club-record deal', 'The England midfielder completes his move from West Ham to Arsenal for a British record fee.', 'Arsenal have confirmed the signing of Declan Rice from West Ham United. The deal, worth £105 million, breaks the British transfer record. Rice has signed a long-term contract and will wear the number 41 shirt. Mikel Arteta described the signing as a "statement of intent" as Arsenal look to build on their impressive campaign. Rice is expected to slot into the heart of Arsenal''s midfield.', 'confirmed_transfer', false, 'Declan Rice Arsenal transfer confirmed', '2023-07-15 10:00:00'),
('kane-bayern-munich-announced', 'Harry Kane completes move to Bayern Munich', 'The England captain leaves Tottenham after 19 years to join the German champions.', 'Bayern Munich have announced the signing of Harry Kane from Tottenham Hotspur. The striker has signed a four-year contract with the Bundesliga champions. The transfer fee is reported to be in the region of €100 million. Kane leaves Tottenham as their all-time record goalscorer and will lead Bayern''s attack as they pursue domestic and European success. The move ends one of the longest-running transfer sagas of the summer.', 'confirmed_transfer', false, 'Harry Kane Bayern Munich transfer confirmed', '2023-08-12 15:00:00'),

-- Gossip
('premier-league-managers-hot-seat', 'Premier League managers under pressure: Who could be next to go?', 'The managerial merry-go-round shows no signs of slowing as several bosses face uncertain futures.', 'The Premier League''s managerial landscape could see significant changes in the coming months. Several clubs have underperformed relative to expectations, and owners are known to be considering their options. The international break often provides a window for change, and we assess which managers might be feeling the heat. From established names to recent appointments, no one is safe in the results business.', 'gossip', false, 'Premier League managers under pressure', '2024-11-10 09:00:00'),
('african-stars-european-interest', 'African stars attracting European interest: Scouting report', 'Several players from the continent are on the radar of top European clubs ahead of the transfer window.', 'Scouts from across Europe have been busy watching African talent in domestic leagues and continental competitions. Young forwards from Ghana, Nigeria, and Senegal are particularly in demand. The success of African players in the Premier League and other top leagues has increased interest. We profile the players most likely to make the move to Europe in the coming months.', 'gossip', false, 'African footballers European transfer interest', '2025-06-01 12:00:00')
ON CONFLICT (slug) DO NOTHING;

-- =============================================================================
-- RESOURCE ITEMS (Betting education - beginner, intermediate, advanced)
-- =============================================================================
-- category_id: 1=beginner, 2=intermediate, 3=advanced (from migration 036)
INSERT INTO resource_items (category_id, slug, title, excerpt, content, type, duration_minutes, featured, sort_order, published_at) VALUES
-- Beginner
(1, 'understanding-odds', 'Understanding betting odds: A beginner''s guide', 'Learn how decimal, fractional, and American odds work and what they mean for your potential returns.', 'Betting odds represent the probability of an outcome and determine your potential profit. Decimal odds (e.g. 2.50) show your total return per unit staked. Fractional odds (e.g. 3/2) express profit relative to stake. American odds use + and - to indicate underdogs and favourites. Understanding implied probability helps you spot value. Always compare odds across bookmakers to get the best price.', 'article', 8, true, 1, NOW()),
(1, 'bankroll-basics', 'Bankroll management: The foundation of successful betting', 'Protect your funds and bet sustainably with these essential bankroll principles.', 'Your bankroll is the total amount you allocate for betting. Never bet more than you can afford to lose. A common rule is to risk 1-5% of your bankroll per bet. Track every bet in a spreadsheet or app. Set monthly limits and stick to them. Avoid chasing losses by increasing stake sizes. Building discipline with bankroll management is the first step to long-term success.', 'article', 10, true, 2, NOW()),
(1, 'types-of-bets', 'Types of football bets explained', 'From match result to accumulators: understand the most common bet types.', 'Match result (1X2) is the simplest: home win, draw, or away win. Both teams to score (BTTS) pays if each side scores. Over/under goals bets on the total number of goals. Accumulators combine multiple selections for higher odds but require all to win. Correct score and first goalscorer offer bigger payouts but are harder to predict. Start simple and expand as you learn.', 'article', 12, false, 3, NOW()),
(1, 'responsible-gambling', 'Responsible gambling: Setting limits and staying in control', 'Bet for entertainment. Know the signs of problem gambling and where to get help.', 'Gambling should be fun, not a way to make money. Set deposit limits before you start. Take regular breaks and never bet when upset or under the influence. Recognise warning signs: chasing losses, betting more than you can afford, hiding your betting from others. Resources like GamCare and BeGambleAware offer free support. If betting stops being enjoyable, stop and seek help.', 'article', 6, true, 4, NOW()),

-- Intermediate
(2, 'value-betting', 'Value betting: Finding edges in the market', 'Learn to identify when odds offer value and build a profitable approach.', 'Value exists when the true probability of an outcome is higher than the odds imply. If you believe a team has a 50% chance of winning but odds are 2.20 (45% implied), that''s value. Build your own probability estimates using form, head-to-head, and key stats. Compare with bookmaker odds. Value betting requires discipline: bet when you have an edge, not on every match. Long-term, value bettors profit even with a moderate win rate.', 'strategy', 15, true, 1, NOW()),
(2, 'form-and-stats', 'Using form and statistics in football betting', 'Key metrics that matter when analysing matches and making informed bets.', 'Recent form (last 5-10 games) matters but can be misleading. Home/away splits reveal venue-dependent performance. Head-to-head history shows psychological edges. Expected goals (xG) indicate whether results are sustainable. Injuries and suspensions significantly impact outcomes. Don''t over-rely on any single metric; combine multiple factors. Create a checklist and apply it consistently.', 'article', 14, true, 2, NOW()),
(2, 'accumulator-strategy', 'Accumulator strategy: When to use them and when to avoid', 'Accumulators can be fun but carry high risk. Learn a balanced approach.', 'Accumulators multiply odds but also multiply risk. One losing selection loses the entire bet. Use them sparingly and for entertainment. If pursuing value, singles often outperform accas long-term. Consider smaller accas (2-4 legs) with stronger selections. Avoid adding "fillers" just to boost odds. Track your acca performance separately from singles to see the real picture.', 'strategy', 10, false, 3, NOW()),
(2, 'odds-movement', 'Reading odds movement: What line moves tell you', 'Odds don''t move randomly. Learn to interpret market signals.', 'Odds movement reflects new information: team news, injuries, or sharp money. Significant early moves often indicate informed action. Compare opening lines with current odds across multiple books. Steam moves (rapid drops) can signal sharp play. Be cautious: sometimes moves are driven by public bias, not value. Use odds movement as one input, not the sole basis for a bet.', 'article', 12, false, 4, NOW()),

-- Advanced
(3, 'closing-line-value', 'Closing line value (CLV): The sharp bettor''s edge', 'Beating the closing line is a key indicator of long-term betting skill.', 'Closing line value measures whether you got a better price than the final market odds. If you bet at 2.10 and the line closes at 1.95, you have positive CLV. Consistently beating the close suggests you have an edge. Bookmakers limit or ban sharp bettors; CLV helps identify who they are. Track your CLV over time. It''s one of the best predictors of long-term profitability.', 'strategy', 18, true, 1, NOW()),
(3, 'betting-models', 'Introduction to betting models', 'Build a simple model to estimate match probabilities.', 'Models combine data to produce probability estimates. Start with goals scored/conceded, home advantage, and form. Use Poisson distribution for goal-based models. Backtest on historical data before betting real money. Refine with additional factors: xG, injuries, motivation. No model is perfect; the goal is to be less wrong than the market. Combine model output with qualitative analysis.', 'strategy', 25, true, 2, NOW()),
(3, 'bankroll-optimization', 'Kelly Criterion and bankroll optimization', 'Mathematically optimal stake sizing for long-term growth.', 'The Kelly Criterion suggests betting a fraction of bankroll proportional to your edge. Full Kelly maximizes growth but has high variance; half-Kelly or quarter-Kelly reduces risk. Formula: f = (bp - q) / b, where b is decimal odds - 1, p is your estimated win probability, q = 1 - p. Requires accurate probability estimates. Used by professional bettors; beginners should use flat or very conservative stakes.', 'strategy', 20, false, 3, NOW())
ON CONFLICT (category_id, slug) DO NOTHING;
