-- 2026 Trending Football News - Add to existing news (keeps all current articles)
-- Run: psql -h localhost -p 5435 -U betrollover -d betrollover -f database/seeds/news-2026-seed.sql
-- Or: docker compose exec -T postgres psql -U betrollover -d betrollover < database/seeds/news-2026-seed.sql

INSERT INTO news_articles (slug, title, excerpt, content, category, featured, meta_description, published_at) VALUES
-- 2026 News (Jan-Feb)
('morocco-first-african-2026-world-cup', 'Morocco become first African side to qualify for 2026 World Cup', 'The Atlas Lions secured their place with a dominant 5-0 victory over Niger in Rabat, clinching top spot in Group E with two matches to spare.', 'Morocco became the first African nation to qualify for the 2026 FIFA World Cup after a commanding 5-0 win over Niger in September 2025. Ismael Saibari scored twice, with Ayoub El Kaabi, Hamza Igamane, and Azzedine Ounahi also on the scoresheet. The Atlas Lions have maintained a near-perfect qualifying record and will make their third consecutive World Cup appearance. With nine automatic spots for Africa in the expanded 48-team tournament, Egypt, Algeria, and Senegal remain in the hunt.', 'news', true, 'Morocco 2026 World Cup qualification', '2026-02-01 10:00:00'),
('fa-cup-fourth-round-2026-chelsea-hull', 'FA Cup fourth round: Chelsea thrash Hull 4-0 as Pedro Neto hits hat-trick', 'Liam Rosenior enjoyed a triumphant return to his former club as Chelsea dominated Hull City in the FA Cup fourth round.', 'Chelsea produced a dominant display to beat Hull City 4-0 in the FA Cup fourth round. Pedro Neto scored a hat-trick in a performance that marked a positive return for head coach Liam Rosenior to his former club. The Blues advance to the fifth round as they continue their pursuit of silverware. Elsewhere, Wrexham advanced after beating Ipswich, while Arsenal faced Wigan and Newcastle overcame Aston Villa.', 'news', true, 'FA Cup fourth round Chelsea Hull 2026', '2026-02-14 18:00:00'),
('premier-league-manager-sackings-feb-2026', 'Premier League managerial chaos: Tottenham and Nottingham Forest sack bosses', 'Thomas Frank and Sean Dyche dismissed as Tottenham appoint Igor Tudor and Forest bring in Vítor Pereira.', 'The Premier League managerial merry-go-round spun into action with Tottenham sacking Thomas Frank after a 2-1 loss to Newcastle left the club 16th. Igor Tudor has agreed to become interim manager. Nottingham Forest also parted ways with Sean Dyche, appointing Vítor Pereira as their fourth head coach of the season. The changes come amid a crucial period in the campaign as clubs battle for survival and European places.', 'news', true, 'Premier League manager sackings February 2026', '2026-02-12 14:00:00'),
('thomas-tuchel-england-contract-2028', 'Thomas Tuchel signs England contract extension through 2028', 'The Three Lions boss targets World Cup glory after committing his future to the national team.', 'Thomas Tuchel has signed a contract extension as England manager, keeping him in charge through the 2028 European Championship and the 2026 World Cup cycle. The former Chelsea and Bayern Munich boss has overseen a strong start to his tenure and is targeting major tournament success. The FA described the extension as a "statement of intent" as England look to build on recent progress.', 'news', true, 'Thomas Tuchel England contract extension', '2026-02-10 11:00:00'),
('arsenal-brentford-draw-lewis-potter', 'Arsenal drop points as Keane Lewis-Potter denies leaders with Brentford equaliser', 'The Gunners'' title hopes suffer a blow after a 1-1 draw at the Gtech Community Stadium.', 'Arsenal''s Premier League title charge hit a setback as Keane Lewis-Potter headed in a late equaliser to earn Brentford a 1-1 draw. The result allowed rivals to close the gap at the top of the table. Mikel Arteta''s side had taken the lead but could not hold on for all three points. The race for the Premier League crown remains wide open with multiple clubs in contention.', 'news', false, 'Arsenal Brentford draw February 2026', '2026-02-15 16:00:00'),
('wrexham-fa-cup-fifth-round-2026', 'Wrexham advance to FA Cup fifth round after beating Ipswich', 'Josh Windass plays key role as the Red Dragons continue their cup run with victory over Championship side.', 'Wrexham secured their place in the FA Cup fifth round with a impressive victory over Ipswich Town. Josh Windass was instrumental in the win as Phil Parkinson''s side continued their remarkable cup journey. The result adds to a memorable season for the Welsh club, who have captured the imagination of football fans worldwide. Other fourth-round results included Oxford 0-1 Sunderland and Stoke 1-2 Fulham.', 'news', false, 'Wrexham FA Cup fifth round 2026', '2026-02-14 20:00:00'),
('womens-champions-league-man-united-atletico', 'Manchester United women dominate Atlético Madrid 3-0 in Champions League playoff', 'Elisabeth Terland and Melvine Malard on target as United take commanding lead into second leg.', 'Manchester United produced a dominant display to beat Atlético Madrid 3-0 in the Women''s Champions League playoff first leg. Elisabeth Terland and Melvine Malard were among the goalscorers as United put themselves in a strong position for the return fixture. The result continues United''s impressive form in European competition and sets up an intriguing second leg in Spain.', 'news', false, 'Man United Women Champions League Atletico 2026', '2026-02-13 19:00:00'),

-- 2026 Confirmed Transfer
('raheem-sterling-feyenoord-chelsea-exit', 'Raheem Sterling joins Feyenoord on loan after Chelsea exit', 'The former England winger mutually terminated his Chelsea contract and chose Feyenoord over 18 other clubs.', 'Raheem Sterling has joined Dutch club Feyenoord on a deal until the end of the season after leaving Chelsea. The 31-year-old mutually terminated his contract with 18 months remaining and reportedly rejected approaches from around 18 clubs before choosing Feyenoord, managed by Robin van Persie. Sterling had been exiled from Chelsea''s first team and spent last season on loan at Arsenal. He said he chose the short-term move to "recapture his joy" for football.', 'confirmed_transfer', true, 'Raheem Sterling Feyenoord transfer 2026', '2026-02-12 12:00:00'),

-- 2026 Transfer Rumour / Africa-relevant
('world-cup-2026-african-qualification-race', '2026 World Cup: African qualification race heats up as Morocco lead the way', 'Nine automatic spots up for grabs with Egypt, Algeria, Senegal, and Nigeria in the hunt.', 'With Morocco already qualified, the race for Africa''s remaining eight automatic World Cup spots intensifies. Egypt and Algeria have strengthened their bids, while Nigeria face a tougher path. The expanded 48-team tournament offers a record nine places for African nations, with the best-placed runners-up entering intercontinental play-offs for a potential tenth berth. Ghana and other contenders will battle in the final qualifying matchdays.', 'transfer_rumour', true, '2026 World Cup Africa qualification', '2026-02-08 09:00:00')
ON CONFLICT (slug) DO NOTHING;
