-- Seed Data: FIFA Top 150 National Teams
-- Full team names, sorted by approximate FIFA ranking

INSERT INTO `national_teams` (`country_code`, `team_name`, `fifa_code`, `fifa_ranking`, `is_active`) VALUES
('ARG', 'Argentina', 'ARG', 1, 1),
('FRA', 'France', 'FRA', 2, 1),
('BRA', 'Brazil', 'BRA', 3, 1),
('ENG', 'England', 'ENG', 4, 1),
('BEL', 'Belgium', 'BEL', 5, 1),
('POR', 'Portugal', 'POR', 6, 1),
('NED', 'Netherlands', 'NED', 7, 1),
('ESP', 'Spain', 'ESP', 8, 1),
('ITA', 'Italy', 'ITA', 9, 1),
('CRO', 'Croatia', 'CRO', 10, 1),
('URU', 'Uruguay', 'URU', 11, 1),
('MAR', 'Morocco', 'MAR', 12, 1),
('USA', 'United States', 'USA', 13, 1),
('COL', 'Colombia', 'COL', 14, 1),
('MEX', 'Mexico', 'MEX', 15, 1),
('GER', 'Germany', 'GER', 16, 1),
('JPN', 'Japan', 'JPN', 17, 1),
('SEN', 'Senegal', 'SEN', 18, 1),
('DEN', 'Denmark', 'DEN', 19, 1),
('POL', 'Poland', 'POL', 20, 1),
('SUI', 'Switzerland', 'SUI', 21, 1),
('IRN', 'Iran', 'IRN', 22, 1),
('KOR', 'South Korea', 'KOR', 23, 1),
('WAL', 'Wales', 'WAL', 24, 1),
('AUS', 'Australia', 'AUS', 25, 1),
('SWE', 'Sweden', 'SWE', 26, 1),
('UKR', 'Ukraine', 'UKR', 27, 1),
('AUT', 'Austria', 'AUT', 28, 1),
('TUN', 'Tunisia', 'TUN', 29, 1),
('CHI', 'Chile', 'CHI', 30, 1),
('ECU', 'Ecuador', 'ECU', 31, 1),
('PER', 'Peru', 'PER', 32, 1),
('NOR', 'Norway', 'NOR', 33, 1),
('CZE', 'Czech Republic', 'CZE', 34, 1),
('HUN', 'Hungary', 'HUN', 35, 1),
('RUS', 'Russia', 'RUS', 36, 1),
('EGY', 'Egypt', 'EGY', 37, 1),
('NGA', 'Nigeria', 'NGA', 38, 1),
('CMR', 'Cameroon', 'CMR', 39, 1),
('GHA', 'Ghana', 'GHA', 40, 1),
('ALG', 'Algeria', 'ALG', 41, 1),
('CIV', 'Ivory Coast', 'CIV', 42, 1),
('TUR', 'Turkey', 'TUR', 43, 1),
('GRE', 'Greece', 'GRE', 44, 1),
('ROU', 'Romania', 'ROU', 45, 1),
('IRL', 'Republic of Ireland', 'IRL', 46, 1),
('SCO', 'Scotland', 'SCO', 47, 1),
('FIN', 'Finland', 'FIN', 48, 1),
('ISL', 'Iceland', 'ISL', 49, 1),
('SRB', 'Serbia', 'SRB', 50, 1),
('SVK', 'Slovakia', 'SVK', 51, 1),
('SVN', 'Slovenia', 'SVN', 52, 1),
('BUL', 'Bulgaria', 'BUL', 53, 1),
('ISR', 'Israel', 'ISR', 54, 1),
('PAR', 'Paraguay', 'PAR', 55, 1),
('VEN', 'Venezuela', 'VEN', 56, 1),
('BOL', 'Bolivia', 'BOL', 57, 1),
('CRC', 'Costa Rica', 'CRC', 58, 1),
('PAN', 'Panama', 'PAN', 59, 1),
('JAM', 'Jamaica', 'JAM', 60, 1),
('HON', 'Honduras', 'HON', 61, 1),
('CAN', 'Canada', 'CAN', 62, 1),
('QAT', 'Qatar', 'QAT', 63, 1),
('SAU', 'Saudi Arabia', 'SAU', 64, 1),
('UAE', 'United Arab Emirates', 'UAE', 65, 1),
('IRQ', 'Iraq', 'IRQ', 66, 1),
('OMA', 'Oman', 'OMA', 67, 1),
('UZB', 'Uzbekistan', 'UZB', 68, 1),
('CHN', 'China', 'CHN', 69, 1),
('THA', 'Thailand', 'THA', 70, 1),
('VIE', 'Vietnam', 'VIE', 71, 1),
('PHI', 'Philippines', 'PHI', 72, 1),
('IDN', 'Indonesia', 'IDN', 73, 1),
('MAS', 'Malaysia', 'MAS', 74, 1),
('SGP', 'Singapore', 'SGP', 75, 1),
('NZL', 'New Zealand', 'NZL', 76, 1),
('FIJ', 'Fiji', 'FIJ', 77, 1),
('PNG', 'Papua New Guinea', 'PNG', 78, 1),
('SOL', 'Solomon Islands', 'SOL', 79, 1),
('TAH', 'Tahiti', 'TAH', 80, 1),
('RSA', 'South Africa', 'RSA', 81, 1),
('ZAF', 'South Africa', 'ZAF', 82, 1),
('KEN', 'Kenya', 'KEN', 83, 1),
('UGA', 'Uganda', 'UGA', 84, 1),
('TAN', 'Tanzania', 'TAN', 85, 1),
('ZIM', 'Zimbabwe', 'ZIM', 86, 1),
('ZAM', 'Zambia', 'ZAM', 87, 1),
('MAD', 'Madagascar', 'MAD', 88, 1),
('MOZ', 'Mozambique', 'MOZ', 89, 1),
('ANG', 'Angola', 'ANG', 90, 1),
('MLI', 'Mali', 'MLI', 91, 1),
('BFA', 'Burkina Faso', 'BFA', 92, 1),
('BEN', 'Benin', 'BEN', 93, 1),
('GAB', 'Gabon', 'GAB', 94, 1),
('GNB', 'Guinea-Bissau', 'GNB', 95, 1),
('GUI', 'Guinea', 'GUI', 96, 1),
('SLE', 'Sierra Leone', 'SLE', 97, 1),
('LBR', 'Liberia', 'LBR', 98, 1),
('TGO', 'Togo', 'TGO', 99, 1),
('NIG', 'Niger', 'NIG', 100, 1),
('CHA', 'Chad', 'CHA', 101, 1),
('CAF', 'Central African Republic', 'CAF', 102, 1),
('STP', 'Sao Tome and Principe', 'STP', 103, 1),
('EQG', 'Equatorial Guinea', 'EQG', 104, 1),
('CPV', 'Cape Verde', 'CPV', 105, 1),
('MTN', 'Mauritania', 'MTN', 106, 1),
('GAM', 'Gambia', 'GAM', 107, 1),
('SEN', 'Senegal', 'SEN', 108, 1),
('GIN', 'Guinea', 'GIN', 109, 1),
('BOT', 'Botswana', 'BOT', 110, 1),
('NAM', 'Namibia', 'NAM', 111, 1),
('SWZ', 'Eswatini', 'SWZ', 112, 1),
('LES', 'Lesotho', 'LES', 113, 1),
('ETH', 'Ethiopia', 'ETH', 114, 1),
('ERI', 'Eritrea', 'ERI', 115, 1),
('DJI', 'Djibouti', 'DJI', 116, 1),
('SOM', 'Somalia', 'SOM', 117, 1),
('SUD', 'Sudan', 'SUD', 118, 1),
('SSD', 'South Sudan', 'SSD', 119, 1),
('BDI', 'Burundi', 'BDI', 120, 1),
('RWA', 'Rwanda', 'RWA', 121, 1),
('COD', 'DR Congo', 'COD', 122, 1),
('COG', 'Congo', 'COG', 123, 1),
('CIV', 'Ivory Coast', 'CIV', 124, 1),
('GHA', 'Ghana', 'GHA', 125, 1),
('TUN', 'Tunisia', 'TUN', 126, 1),
('LBY', 'Libya', 'LBY', 127, 1),
('EGY', 'Egypt', 'EGY', 128, 1),
('SDN', 'Sudan', 'SDN', 129, 1),
('ETH', 'Ethiopia', 'ETH', 130, 1),
('ERI', 'Eritrea', 'ERI', 131, 1),
('DJI', 'Djibouti', 'DJI', 132, 1),
('SOM', 'Somalia', 'SOM', 133, 1),
('YEM', 'Yemen', 'YEM', 134, 1),
('SYR', 'Syria', 'SYR', 135, 1),
('LBN', 'Lebanon', 'LBN', 136, 1),
('JOR', 'Jordan', 'JOR', 137, 1),
('PSE', 'Palestine', 'PSE', 138, 1),
('BHR', 'Bahrain', 'BHR', 139, 1),
('KWT', 'Kuwait', 'KWT', 140, 1),
('YEM', 'Yemen', 'YEM', 141, 1),
('AFG', 'Afghanistan', 'AFG', 142, 1),
('PAK', 'Pakistan', 'PAK', 143, 1),
('IND', 'India', 'IND', 144, 1),
('BAN', 'Bangladesh', 'BAN', 145, 1),
('SRI', 'Sri Lanka', 'SRI', 146, 1),
('NPL', 'Nepal', 'NPL', 147, 1),
('BHU', 'Bhutan', 'BHU', 148, 1),
('MDV', 'Maldives', 'MDV', 149, 1),
('MYA', 'Myanmar', 'MYA', 150, 1)
ON DUPLICATE KEY UPDATE 
    `team_name` = VALUES(`team_name`),
    `fifa_code` = VALUES(`fifa_code`),
    `fifa_ranking` = VALUES(`fifa_ranking`),
    `updated_at` = CURRENT_TIMESTAMP;

