#!/bin/bash

# Manual steps to reset admin password in production
# Run these commands one by one

echo "==================================================================="
echo "MANUAL PRODUCTION PASSWORD RESET"
echo "==================================================================="
echo ""
echo "Password: Admin@123456"
echo "Hash: \$2b\$10\$fEOI2AW2gUg5JVGERSfmoeJ9FGrM40eoAI3Q4hHtuiQzgo8zD3l72"
echo ""
echo "==================================================================="
echo "STEP 1: SSH into VPS"
echo "==================================================================="
echo "ssh root@31.97.57.75"
echo ""
echo "==================================================================="
echo "STEP 2: Get container IP"
echo "==================================================================="
echo "docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' postgres-aw0so4cgcscsgk8c0okggswk-192537349803"
echo ""
echo "==================================================================="
echo "STEP 3: Connect to PostgreSQL (replace CONTAINER_IP with IP from step 2)"
echo "==================================================================="
echo "docker exec -it postgres-aw0so4cgcscsgk8c0okggswk-192537349803 psql -U betrollover -d betrollover"
echo ""
echo "==================================================================="
echo "STEP 4: Run this SQL command"
echo "==================================================================="
echo "UPDATE users SET password = '\$2b\$10\$fEOI2AW2gUg5JVGERSfmoeJ9FGrM40eoAI3Q4hHtuiQzgo8zD3l72' WHERE email = 'admin@betrollover.com';"
echo ""
echo "==================================================================="
echo "STEP 5: Verify the update"
echo "==================================================================="
echo "SELECT email, role, LEFT(password, 30) as password_preview FROM users WHERE email = 'admin@betrollover.com';"
echo ""
echo "==================================================================="
echo "STEP 6: Exit PostgreSQL and SSH"
echo "==================================================================="
echo "\\q"
echo "exit"
echo ""
echo "==================================================================="
echo "DONE! Now try logging in with:"
echo "Email: admin@betrollover.com"
echo "Password: Admin@123456"
echo "==================================================================="
