import { MigrationInterface, QueryRunner } from "typeorm";

export class AddUniqueConstraints1771342706456 implements MigrationInterface {
    name = 'AddUniqueConstraints1771342706456'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" DROP CONSTRAINT "withdrawal_requests_payout_method_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" DROP CONSTRAINT "withdrawal_requests_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "wallet_transactions_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_wallets" DROP CONSTRAINT "user_wallets_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "payout_methods" DROP CONSTRAINT "payout_methods_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "deposit_requests" DROP CONSTRAINT "deposit_requests_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" DROP CONSTRAINT "tipster_requests_reviewed_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" DROP CONSTRAINT "tipster_requests_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "resource_items" DROP CONSTRAINT "resource_items_category_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "tipsters" DROP CONSTRAINT "tipsters_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "tipster_performance_log" DROP CONSTRAINT "tipster_performance_log_tipster_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "tipster_follows" DROP CONSTRAINT "tipster_follows_tipster_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "tipster_follows" DROP CONSTRAINT "tipster_follows_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "fixture_odds" DROP CONSTRAINT "fixture_odds_fixture_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "fixtures" DROP CONSTRAINT "fixtures_league_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "prediction_fixtures" DROP CONSTRAINT "prediction_fixtures_fixture_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "prediction_fixtures" DROP CONSTRAINT "prediction_fixtures_prediction_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "predictions" DROP CONSTRAINT "predictions_tipster_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" DROP CONSTRAINT "ad_campaigns_zone_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "visitor_sessions" DROP CONSTRAINT "visitor_sessions_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_purchased_picks" DROP CONSTRAINT "user_purchased_picks_accumulator_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_purchased_picks" DROP CONSTRAINT "user_purchased_picks_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" DROP CONSTRAINT "pick_marketplace_prediction_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" DROP CONSTRAINT "pick_marketplace_seller_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" DROP CONSTRAINT "pick_marketplace_accumulator_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" DROP CONSTRAINT "escrow_funds_pick_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" DROP CONSTRAINT "escrow_funds_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" DROP CONSTRAINT "accumulator_picks_fixture_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" DROP CONSTRAINT "accumulator_picks_accumulator_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP CONSTRAINT "accumulator_tickets_away_country_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP CONSTRAINT "accumulator_tickets_home_country_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP CONSTRAINT "accumulator_tickets_buyer_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP CONSTRAINT "accumulator_tickets_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_withdrawal_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_withdrawal_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_withdrawal_reference"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email_verification_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wallet_tx_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wallet_tx_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wallet_tx_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wallet_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_deposit_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_deposit_reference"`);
        await queryRunner.query(`DROP INDEX "public"."idx_deposit_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tipster_requests_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tipster_requests_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_resource_items_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_resource_items_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_resource_items_published"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tipsters_roi"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tipsters_is_ai"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tipsters_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tipsters_username"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tipsters_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tipster_performance_tipster"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tipster_performance_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tipster_follows_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tipster_follows_tipster"`);
        await queryRunner.query(`DROP INDEX "public"."idx_odds_fixture"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fixtures_synced_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fixtures_status_scores"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fixtures_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fixtures_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fixtures_league"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fixtures_api_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fixtures_status_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prediction_fixtures_prediction"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prediction_fixtures_fixture_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prediction_fixtures_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_predictions_tipster"`);
        await queryRunner.query(`DROP INDEX "public"."idx_predictions_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_predictions_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_predictions_posted_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_registration_otps_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_registration_otps_expires"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_is_read"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_news_articles_slug"`);
        await queryRunner.query(`DROP INDEX "public"."idx_news_articles_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_news_articles_published"`);
        await queryRunner.query(`DROP INDEX "public"."idx_market_config_enabled"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fixtures_archive_match_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fixtures_archive_original_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_enabled_leagues_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_enabled_leagues_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_enabled_leagues_bookmaker_tier"`);
        await queryRunner.query(`DROP INDEX "public"."idx_smart_coupons_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_smart_coupons_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_content_pages_slug"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ad_campaigns_zone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ad_campaigns_dates"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ad_campaigns_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visitor_sessions_session_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visitor_sessions_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visitor_sessions_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visitor_sessions_page"`);
        await queryRunner.query(`DROP INDEX "public"."idx_analytics_daily_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_purchased_picks_user_acc"`);
        await queryRunner.query(`DROP INDEX "public"."idx_purchased_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_purchased_accumulator"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pick_marketplace_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_marketplace_seller"`);
        await queryRunner.query(`DROP INDEX "public"."idx_marketplace_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pick_marketplace_prediction_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_escrow_funds_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_escrow_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_escrow_pick"`);
        await queryRunner.query(`DROP INDEX "public"."idx_accumulator_picks_fixture_result"`);
        await queryRunner.query(`DROP INDEX "public"."idx_accumulator_picks_accumulator_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_acc_picks_accumulator"`);
        await queryRunner.query(`DROP INDEX "public"."idx_acc_picks_fixture"`);
        await queryRunner.query(`DROP INDEX "public"."idx_accumulator_tickets_user_result"`);
        await queryRunner.query(`DROP INDEX "public"."idx_accumulator_tickets_status_result"`);
        await queryRunner.query(`DROP INDEX "public"."idx_acc_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_acc_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_acc_is_marketplace"`);
        await queryRunner.query(`DROP INDEX "public"."idx_acc_created_at"`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" DROP CONSTRAINT "withdrawal_requests_status_check"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_role_check"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_status_check"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "wallet_transactions_type_check"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "wallet_transactions_status_check"`);
        await queryRunner.query(`ALTER TABLE "user_wallets" DROP CONSTRAINT "user_wallets_status_check"`);
        await queryRunner.query(`ALTER TABLE "paystack_settings" DROP CONSTRAINT "paystack_settings_mode_check"`);
        await queryRunner.query(`ALTER TABLE "payout_methods" DROP CONSTRAINT "payout_methods_type_check"`);
        await queryRunner.query(`ALTER TABLE "deposit_requests" DROP CONSTRAINT "deposit_requests_status_check"`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" DROP CONSTRAINT "tipster_requests_status_check"`);
        await queryRunner.query(`ALTER TABLE "resource_categories" DROP CONSTRAINT "resource_categories_level_check"`);
        await queryRunner.query(`ALTER TABLE "resource_items" DROP CONSTRAINT "resource_items_type_check"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_priority_check"`);
        await queryRunner.query(`ALTER TABLE "news_articles" DROP CONSTRAINT "news_articles_category_check"`);
        await queryRunner.query(`ALTER TABLE "smtp_settings" DROP CONSTRAINT "smtp_settings_encryption_check"`);
        await queryRunner.query(`ALTER TABLE "smart_coupons" DROP CONSTRAINT "smart_coupons_status_check"`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" DROP CONSTRAINT "ad_campaigns_status_check"`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" DROP CONSTRAINT "pick_marketplace_status_check"`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" DROP CONSTRAINT "escrow_funds_status_check"`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" DROP CONSTRAINT "accumulator_picks_match_type_check"`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" DROP CONSTRAINT "accumulator_picks_home_team_type_check"`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" DROP CONSTRAINT "accumulator_picks_away_team_type_check"`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" DROP CONSTRAINT "accumulator_picks_result_check"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP CONSTRAINT "accumulator_tickets_status_check"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP CONSTRAINT "accumulator_tickets_result_check"`);
        await queryRunner.query(`ALTER TABLE "resource_items" DROP CONSTRAINT "resource_items_category_id_slug_key"`);
        await queryRunner.query(`ALTER TABLE "tipster_performance_log" DROP CONSTRAINT "tipster_performance_log_tipster_id_snapshot_date_key"`);
        await queryRunner.query(`ALTER TABLE "tipster_follows" DROP CONSTRAINT "tipster_follows_user_id_tipster_id_key"`);
        await queryRunner.query(`ALTER TABLE "user_purchased_picks" DROP CONSTRAINT "user_purchased_picks_user_id_accumulator_id_key"`);
        await queryRunner.query(`COMMENT ON TABLE "registration_otps" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "fixtures_archive" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "smart_coupons" IS NULL`);
        await queryRunner.query(`CREATE TABLE "password_reset_otps" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "code" character varying NOT NULL, "expires_at" TIMESTAMP NOT NULL, "is_used" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0b4f4c493a1ee383f93ff3a5017" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" DROP COLUMN "match_time"`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" DROP COLUMN "match_type"`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" DROP COLUMN "home_team_type"`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" DROP COLUMN "away_team_type"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "buyer_id"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "purchase_price"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "purchased_at"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "settled_at"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "home_country_id"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "home_team_id"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "away_country_id"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "away_team_id"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "confidence_level"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "views"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "purchases"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "like_count"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "share_count"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "comment_count"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP COLUMN "view_count"`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ALTER COLUMN "currency" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" DROP CONSTRAINT "withdrawal_requests_reference_key"`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "country" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "timezone" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "country_code" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "flag_emoji" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_verified" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."email_verified_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."email_verification_token" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_notifications" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "push_notifications" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "push_notifications" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ALTER COLUMN "currency" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "balance" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "balance" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "currency" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "paystack_settings" ALTER COLUMN "mode" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "paystack_settings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "paystack_settings" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "paystack_settings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "paystack_settings" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payout_methods" DROP CONSTRAINT "payout_methods_user_id_key"`);
        await queryRunner.query(`ALTER TABLE "payout_methods" ALTER COLUMN "is_default" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payout_methods" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payout_methods" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payout_methods" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payout_methods" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "deposit_requests" ALTER COLUMN "currency" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposit_requests" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposit_requests" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "deposit_requests" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposit_requests" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" DROP CONSTRAINT "tipster_requests_user_id_key"`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "resource_categories" ALTER COLUMN "sort_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resource_categories" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resource_categories" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "resource_categories" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resource_categories" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "resource_items" ALTER COLUMN "featured" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resource_items" ALTER COLUMN "sort_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resource_items" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resource_items" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "resource_items" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resource_items" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "is_ai" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "total_predictions" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "total_wins" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "total_losses" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "win_rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "roi" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "current_streak" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "best_streak" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "total_profit" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "avg_odds" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "join_date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "monthly_roi" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "monthly_predictions" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipster_performance_log" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipster_follows" ALTER COLUMN "followed_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leagues" ALTER COLUMN "synced_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "fixture_odds" ALTER COLUMN "synced_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "fixtures" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixtures" ALTER COLUMN "synced_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "prediction_fixtures" ALTER COLUMN "result_status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "prediction_fixtures" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "stake_units" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "predictions"."source" IS NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "posted_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "views" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "likes" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "comments_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "followers_who_placed" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "registration_otps" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "icon" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "priority" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "is_read" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "news_articles" ALTER COLUMN "featured" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_articles" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_articles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "news_articles" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_articles" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sync_status" ALTER COLUMN "last_sync_leagues" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sync_status" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sync_status" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sync_status" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sync_status" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "market_config" ALTER COLUMN "is_enabled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "market_config" ALTER COLUMN "tier" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "market_config" ALTER COLUMN "display_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "market_config" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "market_config" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "market_config" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "market_config" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "fixtures_archive" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixtures_archive" ALTER COLUMN "archived_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixtures_archive" ALTER COLUMN "archived_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "smtp_settings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "smtp_settings" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "smtp_settings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "smtp_settings" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "enabled_leagues" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "enabled_leagues" ALTER COLUMN "priority" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "enabled_leagues" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "enabled_leagues" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "enabled_leagues" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "enabled_leagues" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "smart_coupons" DROP CONSTRAINT "unique_smart_coupon_date"`);
        await queryRunner.query(`ALTER TABLE "smart_coupons" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "smart_coupons" ALTER COLUMN "profit" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "smart_coupons" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "smart_coupons" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "content_pages" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "content_pages" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "content_pages" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "content_pages" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ALTER COLUMN "impressions" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ALTER COLUMN "clicks" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ad_zones" ALTER COLUMN "width" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_zones" ALTER COLUMN "height" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_zones" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_zones" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_zones" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ad_zones" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_zones" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "visitor_sessions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "visitor_sessions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "api_settings" ALTER COLUMN "minimum_roi" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_settings" ALTER COLUMN "minimum_roi" SET DEFAULT '20'`);
        await queryRunner.query(`ALTER TABLE "api_settings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_settings" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "api_settings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_settings" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "unique_visitors" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "unique_sessions" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "page_views" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "registered_users" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "content_creators" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "marketplace_sellers" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "buyers" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "picks_created" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "listings_added" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "purchases" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "revenue" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_purchased_picks" ALTER COLUMN "purchased_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_purchased_picks" ALTER COLUMN "purchased_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" DROP CONSTRAINT "pick_marketplace_accumulator_id_key"`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "purchase_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "view_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "max_purchases" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ALTER COLUMN "result" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "sport" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "total_odds" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "result" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "is_marketplace" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_b78e9e6e1cca09f9b6c70cb991" ON "visitor_sessions" ("session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c8f78f7cfcde073fc140a4d1e" ON "visitor_sessions" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "tipster_follows" ADD CONSTRAINT "UQ_fe8b137882e73549928f9c2828a" UNIQUE ("user_id", "tipster_id")`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" ADD CONSTRAINT "UQ_7b91801960f5e03668665acc62e" UNIQUE ("user_id", "pick_id")`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD CONSTRAINT "UQ_840ec5a7cd95575177dafbe7c55" UNIQUE ("user_id", "title")`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_4796762c619893704abbc3dce65" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ADD CONSTRAINT "FK_7382818ff309cabe40c7a74237a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" ADD CONSTRAINT "FK_1dea7c561c70e06f0241fa73e2d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resource_items" ADD CONSTRAINT "FK_a35c6ddea3e59d004a2c3039069" FOREIGN KEY ("category_id") REFERENCES "resource_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipster_performance_log" ADD CONSTRAINT "FK_380e080097543ad010d22397e59" FOREIGN KEY ("tipster_id") REFERENCES "tipsters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipster_follows" ADD CONSTRAINT "FK_ae47e3ee5eb46cdfd2fbd0493e4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipster_follows" ADD CONSTRAINT "FK_2d53ef819aed7477e85b19591fb" FOREIGN KEY ("tipster_id") REFERENCES "tipsters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fixture_odds" ADD CONSTRAINT "FK_98baa5cceae54bf809470b67a96" FOREIGN KEY ("fixture_id") REFERENCES "fixtures"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fixtures" ADD CONSTRAINT "FK_f978f33d0ebfd2c65321f61a822" FOREIGN KEY ("league_id") REFERENCES "leagues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prediction_fixtures" ADD CONSTRAINT "FK_e0132dd9b0883cbb1c9985149ab" FOREIGN KEY ("prediction_id") REFERENCES "predictions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prediction_fixtures" ADD CONSTRAINT "FK_1e5b30ebbce88eac500a53c5ebd" FOREIGN KEY ("fixture_id") REFERENCES "fixtures"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "predictions" ADD CONSTRAINT "FK_69e5b4b5947fb8fe107be7fb22c" FOREIGN KEY ("tipster_id") REFERENCES "tipsters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ADD CONSTRAINT "FK_a61e8f8e111e044f773659f5ce7" FOREIGN KEY ("zone_id") REFERENCES "ad_zones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ADD CONSTRAINT "FK_9556685201b80b8885df7601339" FOREIGN KEY ("accumulator_id") REFERENCES "accumulator_tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "accumulator_picks" DROP CONSTRAINT "FK_9556685201b80b8885df7601339"`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" DROP CONSTRAINT "FK_a61e8f8e111e044f773659f5ce7"`);
        await queryRunner.query(`ALTER TABLE "predictions" DROP CONSTRAINT "FK_69e5b4b5947fb8fe107be7fb22c"`);
        await queryRunner.query(`ALTER TABLE "prediction_fixtures" DROP CONSTRAINT "FK_1e5b30ebbce88eac500a53c5ebd"`);
        await queryRunner.query(`ALTER TABLE "prediction_fixtures" DROP CONSTRAINT "FK_e0132dd9b0883cbb1c9985149ab"`);
        await queryRunner.query(`ALTER TABLE "fixtures" DROP CONSTRAINT "FK_f978f33d0ebfd2c65321f61a822"`);
        await queryRunner.query(`ALTER TABLE "fixture_odds" DROP CONSTRAINT "FK_98baa5cceae54bf809470b67a96"`);
        await queryRunner.query(`ALTER TABLE "tipster_follows" DROP CONSTRAINT "FK_2d53ef819aed7477e85b19591fb"`);
        await queryRunner.query(`ALTER TABLE "tipster_follows" DROP CONSTRAINT "FK_ae47e3ee5eb46cdfd2fbd0493e4"`);
        await queryRunner.query(`ALTER TABLE "tipster_performance_log" DROP CONSTRAINT "FK_380e080097543ad010d22397e59"`);
        await queryRunner.query(`ALTER TABLE "resource_items" DROP CONSTRAINT "FK_a35c6ddea3e59d004a2c3039069"`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" DROP CONSTRAINT "FK_1dea7c561c70e06f0241fa73e2d"`);
        await queryRunner.query(`ALTER TABLE "user_wallets" DROP CONSTRAINT "FK_7382818ff309cabe40c7a74237a"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_4796762c619893704abbc3dce65"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" DROP CONSTRAINT "UQ_840ec5a7cd95575177dafbe7c55"`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" DROP CONSTRAINT "UQ_7b91801960f5e03668665acc62e"`);
        await queryRunner.query(`ALTER TABLE "tipster_follows" DROP CONSTRAINT "UQ_fe8b137882e73549928f9c2828a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c8f78f7cfcde073fc140a4d1e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b78e9e6e1cca09f9b6c70cb991"`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "is_marketplace" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "result" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "price" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "total_odds" SET DEFAULT 1.000`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ALTER COLUMN "sport" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ALTER COLUMN "result" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "max_purchases" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "view_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "purchase_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ADD CONSTRAINT "pick_marketplace_accumulator_id_key" UNIQUE ("accumulator_id")`);
        await queryRunner.query(`ALTER TABLE "user_purchased_picks" ALTER COLUMN "purchased_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_purchased_picks" ALTER COLUMN "purchased_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "revenue" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "purchases" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "listings_added" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "picks_created" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "buyers" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "marketplace_sellers" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "content_creators" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "registered_users" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "page_views" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "unique_sessions" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analytics_daily" ALTER COLUMN "unique_visitors" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_settings" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "api_settings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_settings" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "api_settings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_settings" ALTER COLUMN "minimum_roi" SET DEFAULT 20.0`);
        await queryRunner.query(`ALTER TABLE "api_settings" ALTER COLUMN "minimum_roi" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "visitor_sessions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "visitor_sessions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_zones" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ad_zones" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_zones" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ad_zones" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_zones" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_zones" ALTER COLUMN "height" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_zones" ALTER COLUMN "width" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ALTER COLUMN "clicks" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ALTER COLUMN "impressions" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "content_pages" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "content_pages" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "content_pages" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "content_pages" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "smart_coupons" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "smart_coupons" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "smart_coupons" ALTER COLUMN "profit" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "smart_coupons" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "smart_coupons" ADD CONSTRAINT "unique_smart_coupon_date" UNIQUE ("date")`);
        await queryRunner.query(`ALTER TABLE "enabled_leagues" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "enabled_leagues" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "enabled_leagues" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "enabled_leagues" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "enabled_leagues" ALTER COLUMN "priority" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "enabled_leagues" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "smtp_settings" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "smtp_settings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "smtp_settings" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "smtp_settings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixtures_archive" ALTER COLUMN "archived_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "fixtures_archive" ALTER COLUMN "archived_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixtures_archive" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "market_config" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "market_config" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "market_config" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "market_config" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "market_config" ALTER COLUMN "display_order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "market_config" ALTER COLUMN "tier" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "market_config" ALTER COLUMN "is_enabled" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sync_status" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sync_status" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sync_status" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sync_status" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sync_status" ALTER COLUMN "last_sync_leagues" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "news_articles" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "news_articles" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_articles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "news_articles" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_articles" ALTER COLUMN "featured" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "is_read" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "priority" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "icon" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "registration_otps" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "followers_who_placed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "comments_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "likes" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "views" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "posted_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "predictions"."source" IS 'api_football = from API-Football predictions endpoint, internal = implied prob from odds'`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "predictions" ALTER COLUMN "stake_units" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "prediction_fixtures" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "prediction_fixtures" ALTER COLUMN "result_status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixtures" ALTER COLUMN "synced_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "fixtures" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixture_odds" ALTER COLUMN "synced_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "leagues" ALTER COLUMN "synced_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tipster_follows" ALTER COLUMN "followed_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipster_performance_log" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "monthly_predictions" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "monthly_roi" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "join_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "avg_odds" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "total_profit" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "best_streak" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "current_streak" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "roi" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "win_rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "total_losses" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "total_wins" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "total_predictions" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipsters" ALTER COLUMN "is_ai" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resource_items" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "resource_items" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resource_items" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "resource_items" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resource_items" ALTER COLUMN "sort_order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resource_items" ALTER COLUMN "featured" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resource_categories" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "resource_categories" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resource_categories" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "resource_categories" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resource_categories" ALTER COLUMN "sort_order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" ADD CONSTRAINT "tipster_requests_user_id_key" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "deposit_requests" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deposit_requests" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposit_requests" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deposit_requests" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposit_requests" ALTER COLUMN "currency" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payout_methods" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payout_methods" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payout_methods" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payout_methods" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payout_methods" ALTER COLUMN "is_default" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payout_methods" ADD CONSTRAINT "payout_methods_user_id_key" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "paystack_settings" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "paystack_settings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "paystack_settings" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "paystack_settings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "paystack_settings" ALTER COLUMN "mode" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "currency" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "balance" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ALTER COLUMN "balance" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ALTER COLUMN "currency" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "push_notifications" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "push_notifications" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_notifications" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."email_verification_token" IS 'Token sent in verification email; cleared after verification'`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."email_verified_at" IS 'When user verified their email; NULL = not verified'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_verified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "flag_emoji" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "country_code" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "timezone" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "country" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ADD CONSTRAINT "withdrawal_requests_reference_key" UNIQUE ("reference")`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ALTER COLUMN "currency" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "view_count" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "comment_count" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "share_count" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "like_count" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "purchases" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "views" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "confidence_level" integer DEFAULT '75'`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "away_team_id" integer`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "away_country_id" integer`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "home_team_id" integer`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "home_country_id" integer`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "settled_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "purchased_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "purchase_price" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD "buyer_id" integer`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ADD "away_team_type" character varying(20) DEFAULT 'club'`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ADD "home_team_type" character varying(20) DEFAULT 'club'`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ADD "match_type" character varying(20) DEFAULT 'league'`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ADD "match_time" TIME`);
        await queryRunner.query(`DROP TABLE "password_reset_otps"`);
        await queryRunner.query(`COMMENT ON TABLE "smart_coupons" IS 'Smart Double Chance coupons - 2-pick accas from API-Football advice (DC only, 70%+ confidence)'`);
        await queryRunner.query(`COMMENT ON TABLE "fixtures_archive" IS 'Archived fixture rows (e.g. match_date older than 90 days) not referenced by any pick; main fixtures table stays lean.'`);
        await queryRunner.query(`COMMENT ON TABLE "registration_otps" IS 'Temporary OTP codes for email verification at registration; cleaned up after use or expiry'`);
        await queryRunner.query(`ALTER TABLE "user_purchased_picks" ADD CONSTRAINT "user_purchased_picks_user_id_accumulator_id_key" UNIQUE ("user_id", "accumulator_id")`);
        await queryRunner.query(`ALTER TABLE "tipster_follows" ADD CONSTRAINT "tipster_follows_user_id_tipster_id_key" UNIQUE ("user_id", "tipster_id")`);
        await queryRunner.query(`ALTER TABLE "tipster_performance_log" ADD CONSTRAINT "tipster_performance_log_tipster_id_snapshot_date_key" UNIQUE ("tipster_id", "snapshot_date")`);
        await queryRunner.query(`ALTER TABLE "resource_items" ADD CONSTRAINT "resource_items_category_id_slug_key" UNIQUE ("category_id", "slug")`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD CONSTRAINT "accumulator_tickets_result_check" CHECK (((result)::text = ANY ((ARRAY['pending'::character varying, 'won'::character varying, 'lost'::character varying, 'void'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD CONSTRAINT "accumulator_tickets_status_check" CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'won'::character varying, 'lost'::character varying, 'void'::character varying, 'pending'::character varying, 'cancelled'::character varying, 'pending_approval'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ADD CONSTRAINT "accumulator_picks_result_check" CHECK (((result)::text = ANY ((ARRAY['pending'::character varying, 'won'::character varying, 'lost'::character varying, 'void'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ADD CONSTRAINT "accumulator_picks_away_team_type_check" CHECK (((away_team_type)::text = ANY ((ARRAY['club'::character varying, 'national'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ADD CONSTRAINT "accumulator_picks_home_team_type_check" CHECK (((home_team_type)::text = ANY ((ARRAY['club'::character varying, 'national'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ADD CONSTRAINT "accumulator_picks_match_type_check" CHECK (((match_type)::text = ANY ((ARRAY['league'::character varying, 'international'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" ADD CONSTRAINT "escrow_funds_status_check" CHECK (((status)::text = ANY ((ARRAY['held'::character varying, 'released'::character varying, 'refunded'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ADD CONSTRAINT "pick_marketplace_status_check" CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'sold'::character varying, 'removed'::character varying, 'expired'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ADD CONSTRAINT "ad_campaigns_status_check" CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'active'::character varying, 'paused'::character varying, 'ended'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "smart_coupons" ADD CONSTRAINT "smart_coupons_status_check" CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'won'::character varying, 'lost'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "smtp_settings" ADD CONSTRAINT "smtp_settings_encryption_check" CHECK (((encryption)::text = ANY ((ARRAY['TLS'::character varying, 'SSL'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "news_articles" ADD CONSTRAINT "news_articles_category_check" CHECK (((category)::text = ANY ((ARRAY['news'::character varying, 'transfer_rumour'::character varying, 'confirmed_transfer'::character varying, 'gossip'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_priority_check" CHECK (((priority)::text = ANY ((ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "resource_items" ADD CONSTRAINT "resource_items_type_check" CHECK (((type)::text = ANY ((ARRAY['article'::character varying, 'strategy'::character varying, 'tool'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "resource_categories" ADD CONSTRAINT "resource_categories_level_check" CHECK (((level)::text = ANY ((ARRAY['beginner'::character varying, 'intermediate'::character varying, 'advanced'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" ADD CONSTRAINT "tipster_requests_status_check" CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "deposit_requests" ADD CONSTRAINT "deposit_requests_status_check" CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "payout_methods" ADD CONSTRAINT "payout_methods_type_check" CHECK (((type)::text = ANY ((ARRAY['mobile_money'::character varying, 'bank'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "paystack_settings" ADD CONSTRAINT "paystack_settings_mode_check" CHECK (((mode)::text = ANY ((ARRAY['live'::character varying, 'test'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ADD CONSTRAINT "user_wallets_status_check" CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'frozen'::character varying, 'suspended'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "wallet_transactions_status_check" CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "wallet_transactions_type_check" CHECK (((type)::text = ANY ((ARRAY['deposit'::character varying, 'withdrawal'::character varying, 'purchase'::character varying, 'refund'::character varying, 'commission'::character varying, 'payout'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_status_check" CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'inactive'::character varying, 'suspended'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_role_check" CHECK (((role)::text = ANY ((ARRAY['user'::character varying, 'tipster'::character varying, 'admin'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ADD CONSTRAINT "withdrawal_requests_status_check" CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "idx_acc_created_at" ON "accumulator_tickets" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_acc_is_marketplace" ON "accumulator_tickets" ("is_marketplace") `);
        await queryRunner.query(`CREATE INDEX "idx_acc_status" ON "accumulator_tickets" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_acc_user_id" ON "accumulator_tickets" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_accumulator_tickets_status_result" ON "accumulator_tickets" ("status", "result") WHERE ((result)::text = 'pending'::text)`);
        await queryRunner.query(`CREATE INDEX "idx_accumulator_tickets_user_result" ON "accumulator_tickets" ("user_id", "result") `);
        await queryRunner.query(`CREATE INDEX "idx_acc_picks_fixture" ON "accumulator_picks" ("fixture_id") `);
        await queryRunner.query(`CREATE INDEX "idx_acc_picks_accumulator" ON "accumulator_picks" ("accumulator_id") `);
        await queryRunner.query(`CREATE INDEX "idx_accumulator_picks_accumulator_id" ON "accumulator_picks" ("accumulator_id") `);
        await queryRunner.query(`CREATE INDEX "idx_accumulator_picks_fixture_result" ON "accumulator_picks" ("result", "fixture_id") WHERE ((fixture_id IS NOT NULL) AND ((result)::text = 'pending'::text))`);
        await queryRunner.query(`CREATE INDEX "idx_escrow_pick" ON "escrow_funds" ("pick_id") `);
        await queryRunner.query(`CREATE INDEX "idx_escrow_user" ON "escrow_funds" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_escrow_funds_status" ON "escrow_funds" ("status") WHERE ((status)::text = 'pending'::text)`);
        await queryRunner.query(`CREATE INDEX "idx_pick_marketplace_prediction_id" ON "pick_marketplace" ("prediction_id") `);
        await queryRunner.query(`CREATE INDEX "idx_marketplace_status" ON "pick_marketplace" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_marketplace_seller" ON "pick_marketplace" ("seller_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pick_marketplace_status" ON "pick_marketplace" ("status") WHERE ((status)::text = 'active'::text)`);
        await queryRunner.query(`CREATE INDEX "idx_purchased_accumulator" ON "user_purchased_picks" ("accumulator_id") `);
        await queryRunner.query(`CREATE INDEX "idx_purchased_user" ON "user_purchased_picks" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_purchased_picks_user_acc" ON "user_purchased_picks" ("user_id", "accumulator_id") `);
        await queryRunner.query(`CREATE INDEX "idx_analytics_daily_date" ON "analytics_daily" ("date") `);
        await queryRunner.query(`CREATE INDEX "idx_visitor_sessions_page" ON "visitor_sessions" ("page") `);
        await queryRunner.query(`CREATE INDEX "idx_visitor_sessions_created_at" ON "visitor_sessions" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_visitor_sessions_user_id" ON "visitor_sessions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_visitor_sessions_session_id" ON "visitor_sessions" ("session_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ad_campaigns_status" ON "ad_campaigns" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_ad_campaigns_dates" ON "ad_campaigns" ("start_date", "end_date") `);
        await queryRunner.query(`CREATE INDEX "idx_ad_campaigns_zone" ON "ad_campaigns" ("zone_id") `);
        await queryRunner.query(`CREATE INDEX "idx_content_pages_slug" ON "content_pages" ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_smart_coupons_status" ON "smart_coupons" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_smart_coupons_date" ON "smart_coupons" ("date") `);
        await queryRunner.query(`CREATE INDEX "idx_enabled_leagues_bookmaker_tier" ON "enabled_leagues" ("bookmaker_tier") WHERE (bookmaker_tier IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_enabled_leagues_category" ON "enabled_leagues" ("category") WHERE (category IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_enabled_leagues_active" ON "enabled_leagues" ("is_active", "priority") `);
        await queryRunner.query(`CREATE INDEX "idx_fixtures_archive_original_id" ON "fixtures_archive" ("original_id") `);
        await queryRunner.query(`CREATE INDEX "idx_fixtures_archive_match_date" ON "fixtures_archive" ("match_date") `);
        await queryRunner.query(`CREATE INDEX "idx_market_config_enabled" ON "market_config" ("is_enabled", "tier", "display_order") `);
        await queryRunner.query(`CREATE INDEX "idx_news_articles_published" ON "news_articles" ("published_at") `);
        await queryRunner.query(`CREATE INDEX "idx_news_articles_category" ON "news_articles" ("category") `);
        await queryRunner.query(`CREATE INDEX "idx_news_articles_slug" ON "news_articles" ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_notif_created" ON "notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_notif_is_read" ON "notifications" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "idx_notif_user" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_registration_otps_expires" ON "registration_otps" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_registration_otps_email" ON "registration_otps" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_predictions_posted_at" ON "predictions" ("posted_at") `);
        await queryRunner.query(`CREATE INDEX "idx_predictions_date" ON "predictions" ("prediction_date") `);
        await queryRunner.query(`CREATE INDEX "idx_predictions_status" ON "predictions" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_predictions_tipster" ON "predictions" ("tipster_id") `);
        await queryRunner.query(`CREATE INDEX "idx_prediction_fixtures_status" ON "prediction_fixtures" ("result_status") `);
        await queryRunner.query(`CREATE INDEX "idx_prediction_fixtures_fixture_id" ON "prediction_fixtures" ("fixture_id") `);
        await queryRunner.query(`CREATE INDEX "idx_prediction_fixtures_prediction" ON "prediction_fixtures" ("prediction_id") `);
        await queryRunner.query(`CREATE INDEX "idx_fixtures_status_date" ON "fixtures" ("match_date", "status") WHERE ((status)::text = ANY ((ARRAY['FT'::character varying, '1H'::character varying, 'HT'::character varying, '2H'::character varying, 'ET'::character varying, 'BT'::character varying, 'P'::character varying])::text[]))`);
        await queryRunner.query(`CREATE INDEX "idx_fixtures_api_id" ON "fixtures" ("api_id") `);
        await queryRunner.query(`CREATE INDEX "idx_fixtures_league" ON "fixtures" ("league_id") `);
        await queryRunner.query(`CREATE INDEX "idx_fixtures_status" ON "fixtures" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_fixtures_date" ON "fixtures" ("match_date") `);
        await queryRunner.query(`CREATE INDEX "idx_fixtures_status_scores" ON "fixtures" ("status", "home_score", "away_score") WHERE (((status)::text = 'FT'::text) AND (home_score IS NOT NULL) AND (away_score IS NOT NULL))`);
        await queryRunner.query(`CREATE INDEX "idx_fixtures_synced_at" ON "fixtures" ("synced_at") WHERE (synced_at IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_odds_fixture" ON "fixture_odds" ("fixture_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tipster_follows_tipster" ON "tipster_follows" ("tipster_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tipster_follows_user" ON "tipster_follows" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tipster_performance_date" ON "tipster_performance_log" ("snapshot_date") `);
        await queryRunner.query(`CREATE INDEX "idx_tipster_performance_tipster" ON "tipster_performance_log" ("tipster_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tipsters_user_id" ON "tipsters" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tipsters_username" ON "tipsters" ("username") `);
        await queryRunner.query(`CREATE INDEX "idx_tipsters_active" ON "tipsters" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_tipsters_is_ai" ON "tipsters" ("is_ai") `);
        await queryRunner.query(`CREATE INDEX "idx_tipsters_roi" ON "tipsters" ("roi") `);
        await queryRunner.query(`CREATE INDEX "idx_resource_items_published" ON "resource_items" ("published_at") `);
        await queryRunner.query(`CREATE INDEX "idx_resource_items_type" ON "resource_items" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_resource_items_category" ON "resource_items" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tipster_requests_user" ON "tipster_requests" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tipster_requests_status" ON "tipster_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_deposit_status" ON "deposit_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_deposit_reference" ON "deposit_requests" ("reference") `);
        await queryRunner.query(`CREATE INDEX "idx_deposit_user" ON "deposit_requests" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_wallet_user" ON "user_wallets" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_wallet_tx_created" ON "wallet_transactions" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_wallet_tx_type" ON "wallet_transactions" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_wallet_tx_user" ON "wallet_transactions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email_verification_token" ON "users" ("email_verification_token") WHERE (email_verification_token IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_withdrawal_reference" ON "withdrawal_requests" ("reference") `);
        await queryRunner.query(`CREATE INDEX "idx_withdrawal_status" ON "withdrawal_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_withdrawal_user" ON "withdrawal_requests" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD CONSTRAINT "accumulator_tickets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD CONSTRAINT "accumulator_tickets_buyer_id_fkey" FOREIGN KEY ("buyer_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD CONSTRAINT "accumulator_tickets_home_country_id_fkey" FOREIGN KEY ("home_country_id") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accumulator_tickets" ADD CONSTRAINT "accumulator_tickets_away_country_id_fkey" FOREIGN KEY ("away_country_id") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ADD CONSTRAINT "accumulator_picks_accumulator_id_fkey" FOREIGN KEY ("accumulator_id") REFERENCES "accumulator_tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accumulator_picks" ADD CONSTRAINT "accumulator_picks_fixture_id_fkey" FOREIGN KEY ("fixture_id") REFERENCES "fixtures"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" ADD CONSTRAINT "escrow_funds_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_funds" ADD CONSTRAINT "escrow_funds_pick_id_fkey" FOREIGN KEY ("pick_id") REFERENCES "accumulator_tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ADD CONSTRAINT "pick_marketplace_accumulator_id_fkey" FOREIGN KEY ("accumulator_id") REFERENCES "accumulator_tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ADD CONSTRAINT "pick_marketplace_seller_id_fkey" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pick_marketplace" ADD CONSTRAINT "pick_marketplace_prediction_id_fkey" FOREIGN KEY ("prediction_id") REFERENCES "predictions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_purchased_picks" ADD CONSTRAINT "user_purchased_picks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_purchased_picks" ADD CONSTRAINT "user_purchased_picks_accumulator_id_fkey" FOREIGN KEY ("accumulator_id") REFERENCES "accumulator_tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visitor_sessions" ADD CONSTRAINT "visitor_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ad_campaigns" ADD CONSTRAINT "ad_campaigns_zone_id_fkey" FOREIGN KEY ("zone_id") REFERENCES "ad_zones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "predictions" ADD CONSTRAINT "predictions_tipster_id_fkey" FOREIGN KEY ("tipster_id") REFERENCES "tipsters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prediction_fixtures" ADD CONSTRAINT "prediction_fixtures_prediction_id_fkey" FOREIGN KEY ("prediction_id") REFERENCES "predictions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prediction_fixtures" ADD CONSTRAINT "prediction_fixtures_fixture_id_fkey" FOREIGN KEY ("fixture_id") REFERENCES "fixtures"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fixtures" ADD CONSTRAINT "fixtures_league_id_fkey" FOREIGN KEY ("league_id") REFERENCES "leagues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fixture_odds" ADD CONSTRAINT "fixture_odds_fixture_id_fkey" FOREIGN KEY ("fixture_id") REFERENCES "fixtures"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipster_follows" ADD CONSTRAINT "tipster_follows_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipster_follows" ADD CONSTRAINT "tipster_follows_tipster_id_fkey" FOREIGN KEY ("tipster_id") REFERENCES "tipsters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipster_performance_log" ADD CONSTRAINT "tipster_performance_log_tipster_id_fkey" FOREIGN KEY ("tipster_id") REFERENCES "tipsters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipsters" ADD CONSTRAINT "tipsters_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resource_items" ADD CONSTRAINT "resource_items_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "resource_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" ADD CONSTRAINT "tipster_requests_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipster_requests" ADD CONSTRAINT "tipster_requests_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deposit_requests" ADD CONSTRAINT "deposit_requests_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payout_methods" ADD CONSTRAINT "payout_methods_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ADD CONSTRAINT "user_wallets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "wallet_transactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ADD CONSTRAINT "withdrawal_requests_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ADD CONSTRAINT "withdrawal_requests_payout_method_id_fkey" FOREIGN KEY ("payout_method_id") REFERENCES "payout_methods"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

}
