-- ============================================
-- Phase 2: Seed 25 AI Tipsters
-- Inserts AI tipsters from ai-tipsters.config.ts
-- Idempotent: ON CONFLICT updates config fields
-- ============================================

INSERT INTO tipsters (username, display_name, avatar_url, bio, is_ai, tipster_type, personality_profile) VALUES
('SafetyFirstPro', 'Safety First Pro', '/avatars/safety_first.png', 'Conservative approach. Favorites only. Steady profits over flashy wins.', true, 'ai', '{"risk_level":"conservative","target_odds_min":1.8,"target_odds_max":2.5,"min_win_probability":0.68,"min_expected_value":0.08,"leagues_focus":["Premier League","La Liga","Serie A"],"bet_types":["1X2"],"max_daily_predictions":1}'::jsonb),
('TheBankroller', 'The Bankroller', '/avatars/bankroller.png', 'Building the bankroll brick by brick. Low odds, high confidence.', true, 'ai', '{"risk_level":"conservative","target_odds_min":1.6,"target_odds_max":2.2,"min_win_probability":0.7,"min_expected_value":0.07,"leagues_focus":["Premier League","Bundesliga"],"bet_types":["1X2","Over/Under"],"max_daily_predictions":1}'::jsonb),
('SteadyEddie', 'Steady Eddie', '/avatars/steady_eddie.png', 'Consistent returns. No gambles, just value.', true, 'ai', '{"risk_level":"conservative","target_odds_min":1.7,"target_odds_max":2.4,"min_win_probability":0.69,"min_expected_value":0.08,"leagues_focus":["Premier League","Ligue 1"],"bet_types":["1X2"],"max_daily_predictions":1}'::jsonb),
('TheAnalyst', 'The Analyst', '/avatars/analyst.png', 'Data-driven predictions. Stats don''t lie.', true, 'ai', '{"risk_level":"balanced","target_odds_min":2,"target_odds_max":3.5,"min_win_probability":0.62,"min_expected_value":0.06,"leagues_focus":["Premier League","La Liga","Serie A","Bundesliga"],"bet_types":["1X2","BTTS","Over/Under"],"max_daily_predictions":2}'::jsonb),
('PremierLeaguePro', 'Premier League Pro', '/avatars/epl_pro.png', 'EPL specialist. Know the league inside out.', true, 'ai', '{"risk_level":"balanced","target_odds_min":2.2,"target_odds_max":3.8,"min_win_probability":0.6,"min_expected_value":0.05,"leagues_focus":["Premier League"],"bet_types":["1X2","Over/Under","BTTS"],"max_daily_predictions":2}'::jsonb),
('LaLigaLegend', 'La Liga Legend', '/avatars/laliga_legend.png', 'Spanish football expert. Tiki-taka predictions.', true, 'ai', '{"risk_level":"balanced","target_odds_min":2.1,"target_odds_max":3.6,"min_win_probability":0.61,"min_expected_value":0.06,"leagues_focus":["La Liga"],"bet_types":["1X2","BTTS"],"max_daily_predictions":2}'::jsonb),
('ValueHunter', 'Value Hunter', '/avatars/value_hunter.png', 'Only bet when odds are in my favor. Value is everything.', true, 'ai', '{"risk_level":"balanced","target_odds_min":2.3,"target_odds_max":4,"min_win_probability":0.58,"min_expected_value":0.1,"leagues_focus":["Premier League","Serie A","Bundesliga"],"bet_types":["1X2"],"max_daily_predictions":1}'::jsonb),
('FormExpert', 'Form Expert', '/avatars/form_expert.png', 'Current form > history. Riding the momentum.', true, 'ai', '{"risk_level":"balanced","target_odds_min":2,"target_odds_max":3.4,"min_win_probability":0.63,"min_expected_value":0.06,"leagues_focus":["Premier League","La Liga","Bundesliga"],"bet_types":["1X2","Over/Under"],"max_daily_predictions":2}'::jsonb),
('HighRollerHQ', 'High Roller HQ', '/avatars/high_roller.png', 'Go big or go home. Premium selections.', true, 'ai', '{"risk_level":"aggressive","target_odds_min":2.8,"target_odds_max":5,"min_win_probability":0.55,"min_expected_value":0.05,"leagues_focus":["Premier League","La Liga","Serie A","Bundesliga","Ligue 1"],"bet_types":["1X2","BTTS","Over/Under"],"max_daily_predictions":2}'::jsonb),
('TheGambler', 'The Gambler', '/avatars/gambler.png', 'Fortune favors the bold. High risk, high reward.', true, 'ai', '{"risk_level":"aggressive","target_odds_min":3,"target_odds_max":5,"min_win_probability":0.52,"min_expected_value":0.04,"leagues_focus":["All"],"bet_types":["1X2","BTTS","Over/Under","Correct Score"],"max_daily_predictions":3}'::jsonb),
('UnderdogKing', 'Underdog King', '/avatars/underdog_king.png', 'Specialist in finding value in underdogs.', true, 'ai', '{"risk_level":"aggressive","target_odds_min":2.5,"target_odds_max":4.5,"min_win_probability":0.57,"min_expected_value":0.07,"leagues_focus":["Premier League","Championship","La Liga"],"bet_types":["1X2"],"preference":"underdogs","max_daily_predictions":2}'::jsonb),
('BTTSMaster', 'BTTS Master', '/avatars/btts_master.png', 'Both Teams To Score specialist. Goals guaranteed.', true, 'ai', '{"risk_level":"balanced","target_odds_min":2,"target_odds_max":3.5,"min_win_probability":0.6,"min_expected_value":0.06,"leagues_focus":["Premier League","Bundesliga"],"bet_types":["BTTS"],"max_daily_predictions":2}'::jsonb),
('OverUnderGuru', 'Over/Under Guru', '/avatars/over_under_guru.png', 'Goals market expert. Over 2.5 specialist.', true, 'ai', '{"risk_level":"balanced","target_odds_min":1.9,"target_odds_max":3.2,"min_win_probability":0.62,"min_expected_value":0.06,"leagues_focus":["Premier League","Bundesliga","Serie A"],"bet_types":["Over/Under"],"max_daily_predictions":2}'::jsonb),
('ChampionshipChamp', 'Championship Champ', '/avatars/championship_champ.png', 'English Championship specialist. Know every team.', true, 'ai', '{"risk_level":"balanced","target_odds_min":2.1,"target_odds_max":3.7,"min_win_probability":0.6,"min_expected_value":0.06,"leagues_focus":["Championship"],"bet_types":["1X2","BTTS"],"max_daily_predictions":2}'::jsonb),
('BundesligaBoss', 'Bundesliga Boss', '/avatars/bundesliga_boss.png', 'German football expert. Efficiency meets goals.', true, 'ai', '{"risk_level":"balanced","target_odds_min":2,"target_odds_max":3.5,"min_win_probability":0.61,"min_expected_value":0.06,"leagues_focus":["Bundesliga"],"bet_types":["1X2","Over/Under"],"max_daily_predictions":2}'::jsonb),
('SerieASavant', 'Serie A Savant', '/avatars/serie_a_savant.png', 'Italian football mastermind. Tactical genius.', true, 'ai', '{"risk_level":"balanced","target_odds_min":2.1,"target_odds_max":3.6,"min_win_probability":0.61,"min_expected_value":0.06,"leagues_focus":["Serie A"],"bet_types":["1X2","Under 2.5"],"max_daily_predictions":2}'::jsonb),
('Ligue1Lion', 'Ligue 1 Lion', '/avatars/ligue1_lion.png', 'French football specialist. PSG and beyond.', true, 'ai', '{"risk_level":"balanced","target_odds_min":2,"target_odds_max":3.5,"min_win_probability":0.62,"min_expected_value":0.06,"leagues_focus":["Ligue 1"],"bet_types":["1X2","BTTS"],"max_daily_predictions":2}'::jsonb),
('TopSixSniper', 'Top Six Sniper', '/avatars/top_six_sniper.png', 'Big 6 EPL specialist. Elite teams only.', true, 'ai', '{"risk_level":"conservative","target_odds_min":1.7,"target_odds_max":2.5,"min_win_probability":0.67,"min_expected_value":0.07,"leagues_focus":["Premier League"],"team_filter":["top_6"],"bet_types":["1X2"],"max_daily_predictions":1}'::jsonb),
('StatsMachine', 'Stats Machine', '/avatars/stats_machine.png', 'Pure mathematics. No emotions, just numbers.', true, 'ai', '{"risk_level":"balanced","target_odds_min":2.2,"target_odds_max":3.8,"min_win_probability":0.59,"min_expected_value":0.08,"leagues_focus":["All"],"bet_types":["1X2","Over/Under","BTTS"],"max_daily_predictions":2}'::jsonb),
('HomeHeroes', 'Home Heroes', '/avatars/home_heroes.png', 'Home advantage is real. Fortress teams only.', true, 'ai', '{"risk_level":"conservative","target_odds_min":1.6,"target_odds_max":2.3,"min_win_probability":0.69,"min_expected_value":0.07,"leagues_focus":["All"],"selection_filter":"home_only","bet_types":["1X2"],"max_daily_predictions":2}'::jsonb),
('CleanSheetChaser', 'Clean Sheet Chaser', '/avatars/clean_sheet_chaser.png', 'Defense wins championships. Under 2.5 goals specialist.', true, 'ai', '{"risk_level":"balanced","target_odds_min":1.9,"target_odds_max":3.2,"min_win_probability":0.62,"min_expected_value":0.06,"leagues_focus":["Serie A","La Liga"],"bet_types":["Under 2.5"],"max_daily_predictions":2}'::jsonb),
('LateBloomer', 'Late Bloomer', '/avatars/late_bloomer.png', 'Second half specialist. Teams that finish strong.', true, 'ai', '{"risk_level":"balanced","target_odds_min":2.1,"target_odds_max":3.6,"min_win_probability":0.6,"min_expected_value":0.06,"leagues_focus":["All"],"bet_types":["1X2","Over/Under"],"max_daily_predictions":2}'::jsonb),
('WeekendWarrior', 'Weekend Warrior', '/avatars/weekend_warrior.png', 'Saturday & Sunday predictions only. Weekend expert.', true, 'ai', '{"risk_level":"balanced","target_odds_min":2,"target_odds_max":3.5,"min_win_probability":0.61,"min_expected_value":0.06,"leagues_focus":["Premier League","La Liga"],"active_days":["Saturday","Sunday"],"bet_types":["1X2","BTTS"],"max_daily_predictions":3}'::jsonb),
('MidweekMagic', 'Midweek Magic', '/avatars/midweek_magic.png', 'Midweek fixtures specialist. Rotation and fatigue expert.', true, 'ai', '{"risk_level":"aggressive","target_odds_min":2.5,"target_odds_max":4.2,"min_win_probability":0.56,"min_expected_value":0.05,"leagues_focus":["All"],"active_days":["Tuesday","Wednesday","Thursday"],"bet_types":["1X2","BTTS"],"max_daily_predictions":2}'::jsonb),
('ConsistentCarl', 'Consistent Carl', '/avatars/consistent_carl.png', '70%+ win rate. Small but steady profits.', true, 'ai', '{"risk_level":"conservative","target_odds_min":1.5,"target_odds_max":2,"min_win_probability":0.75,"min_expected_value":0.07,"leagues_focus":["Premier League","Bundesliga"],"bet_types":["1X2"],"max_daily_predictions":1}'::jsonb)
ON CONFLICT (username) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  avatar_url = EXCLUDED.avatar_url,
  bio = EXCLUDED.bio,
  is_ai = EXCLUDED.is_ai,
  tipster_type = EXCLUDED.tipster_type,
  personality_profile = EXCLUDED.personality_profile,
  updated_at = NOW();
